name: Run tests (jest)

on: [push, pull_request]

jobs:
  tester:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: installing modules
        run: npm install
      - name: running tests
        run: npm run test
      - name: running coverage
        run: npm run test:coverage
